{% set name = "jlab-enhanced-cell-toolbar" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a34cc58e2619d74f4287a80057bdc54fc6bf775afbbd6133ef21b7a6c1e36758

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - nodejs >=12.0.0
  host:
    - python >=3.7
    - pip
    - jupyterlab >=3.1,<4
    - jupyter-packaging >=0.10.0,<2.0.0
  run:
    - python >=3.7

test:
  requires:
    - nodejs >=12.0.0
    - jupyterlab >=3.1,<4
    - pip
  commands:
    - pip check
    - jupyter labextension list 2>&1 | grep -ie "@jlab-enhanced/cell-toolbar.*OK"
    - python -m jupyterlab.browser_check  # [not linux]

about:
  home: https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A cell toolbar for JupyterLab.
  dev_url: https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar

extra:
  recipe-maintainers:
    - fcollonval
