{% set name = "jlab-enhanced-cell-toolbar" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23a726d91006560298dd8c236394ee94709add9690f7f306d71dc50a05b55231

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - nodejs >=12.0.0
  host:
    - python >=3.6
    - pip
    - jupyterlab >=3.0.0
    - jupyter-packaging >=0.7.9,<0.8.0
  run:
    - python >=3.6
    - jupyterlab >=3.0.0

test:
  requires:
    - nodejs >=12.0.0
  commands:
    - jupyter labextension list 2>&1 | grep -ie "@jlab-enhanced/cell-toolbar.*OK"
    - python -m jupyterlab.browser_check  # [not linux]

about:
  home: https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A cell toolbar for JupyterLab.
  dev_url: https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar

extra:
  recipe-maintainers:
    - fcollonval
